# ~/.tmux.conf

##### ====== GENERAL ====== #####

set -g mouse on
set -g default-terminal "tmux-256color"
set -g history-limit 10000

# Start windows and panes at 1 (nicer UX)
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# Don't rename windows automatically
set -g allow-rename off

##### ====== TPM PLUGINS ====== #####


# janoamaral/tokyo-night-tmux    \

# Plugin manager
set -g @tpm_plugins '             \
   tmux-plugins/tpm               \
   tmux-plugins/tmux-sensible     \
   tmux-plugins/tmux-resurrect    \
   TanglingTreats/tmux-everforest \
 '

# TokyoNight theme
# set -g @tokyo-night-tmux_theme night   # night | storm | moon | day
# set -g @tokyo-night-tmux_transparent 1   # 1 = transparent | 0 = solid (default)
#
# set -g @tokyo-night-tmux_show_git 1             # local git status
# set -g @tokyo-night-tmux_show_battery_widget 1  # battery level
# set -g @tokyo-night-tmux_show_path 1            # current path
# set -g @tokyo-night-tmux_show_hostname 1        # machine hostname

set -g @tmux-everforest 'dark-medium' # Sets the option to select the theme. Also the default.
# Add '-xterm' to the back of the name for xterm256 compatibility
# E.g. 'dark-medium-xterm'

##### ====== PANE ====== #####

set -g pane-border-status off
set -g pane-border-format ""

##### ====== VIM NAVIGATION ====== #####

is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?\.?(view|n?vim?x?)(-wrapped)?(diff)?$'"

bind-key -n C-h if-shell "$is_vim" 'send-keys C-h' 'select-pane -L'
bind-key -n C-j if-shell "$is_vim" 'send-keys C-j' 'select-pane -D'
bind-key -n C-k if-shell "$is_vim" 'send-keys C-k' 'select-pane -U'
bind-key -n C-l if-shell "$is_vim" 'send-keys C-l' 'select-pane -R'

bind-key -T copy-mode-vi C-h select-pane -L
bind-key -T copy-mode-vi C-j select-pane -D
bind-key -T copy-mode-vi C-k select-pane -U
bind-key -T copy-mode-vi C-l select-pane -R

##### ====== SPLITS ====== #####

bind | split-window -h
bind - split-window -v

bind r source-file ~/.config/tmux.conf \; display-message "Config reloaded!"

run '~/.tmux/plugins/tpm/tpm'
